### ISSUE TITLE
fix(types): TS2339 errors in current-conversation-bindings.ts after fs-safe refactor

### ISSUE THREAD

**Issue by NOVA-Openclaw** [NOVA-Openclaw/nova-openclaw#39]
## Problem

Every CI run on `main` has been failing since May 4th (~15+ consecutive failures) due to TypeScript strict checking errors introduced by the upstream merge of PR #77918 (`[codex] Extract filesystem safety primitives`).

The refactor replaced the internal `loadJsonFile` implementation with `@openclaw/fs-safe/json` primitives. The `tryReadJsonSync<T>` function from `fs-safe` appears to resolve to a narrower type than the old `loadJsonFile<T = unknown>` signature, causing TS to see the return as `{}` rather than `T`.

## Error

```
src/infra/outbound/current-conversation-bindings.ts(71,28): error TS2339: Property 'version' does not exist on type '{}'
src/infra/outbound/current-conversation-bindings.ts(71,79): error TS2339: Property 'bindings' does not exist on type '{}'
```

Affects **all** CI jobs: `build-artifacts`, `check-strict-smoke`, `check-test-types`, `check-prod-types`, `check-lint`, `check-additional-extension-channels`, `check-additional-extension-bundled`.

Additionally, `check-test-types` has secondary errors in test files:
- `openai-transport-stream.test.ts(2757)` — `unsupportedToolSchemaKeywords` not assignable to `OpenAIModeModel`
- `pi-embedded-runner/openai-stream-wrappers.test.ts(54)` — type conversion mismatch for `Model<"openai-completions">`

## Affected Code

`src/infra/outbound/current-conversation-bindings.ts` line 71:
```typescript
const parsed = loadJsonFile(resolveBindingsFilePath());
const bindings = parsed?.version === CURRENT_BINDINGS_FILE_VERSION ? parsed.bindings : [];
```

`loadJsonFile` is defined in `src/infra/json-file.ts` and now delegates to `tryReadJsonSync` from `@openclaw/fs-safe/json`. The generic type parameter `T = unknown` should flow through, but the compiled type surface from `fs-safe` apparently narrows it.

## Impact

- **Runtime:** No impact — production builds use `build:docker` which skips the DTS/strict type-check step
- **CI:** 100% failure rate on `main` since the merge, running every ~4 hours on schedule
- **Development:** Blocks any PR CI checks from passing

## Introduced By

Upstream commit `538605ff44` merged May 6, 2026 — `[codex] Extract filesystem safety primitives (#77918)` by Peter Steinberger.

## Proposed Fix

Add an explicit type assertion or interface for the bindings file shape:

```typescript
interface BindingsFile {
  version: number;
  bindings: BindingRecord[];
}

const parsed = loadJsonFile<BindingsFile>(resolveBindingsFilePath());
```

Or a minimal inline assertion:
```typescript
const parsed = loadJsonFile(resolveBindingsFilePath()) as { version?: number; bindings?: unknown[] } | undefined;
```

The test file errors may also need type adjustments for the updated `Model` and `OpenAICompletionsCompat` interfaces.
