### ISSUE TITLE
TS2304: Cannot find name 'assistantForFailover' in embedded-agent-runner/run.ts — 4th file broken by v2026.7.1 merge (980a96f)

### ISSUE THREAD

**Issue by NOVA-Openclaw** [NOVA-Openclaw/nova-openclaw#152]
## Summary
`src/agents/embedded-agent-runner/run.ts:3543` references `assistantForFailover`, which is not defined or imported anywhere in the file:

```
src/agents/embedded-agent-runner/run.ts(3543,73): error TS2304: Cannot find name 'assistantForFailover'.
```

## Origin
Introduced by the same v2026.7.1 merge commit `980a96f653` that caused #134, but in a **4th file** never enumerated in #134's scope. Sibling defect with a different failure mode: **missing identifier** (variable/parameter likely dropped or renamed during merge conflict resolution) vs. #134's duplicate identifiers.

## Impact
- Already broken on `main` (pre-existing; not introduced by PR #151).
- Blocks 13 CI jobs on PR #151 (the #134 fix) from reaching green — those jobs fail typecheck before exercising the fixed code.
- PR #151 independently proved correct: 45 previously-failing CI jobs on main now pass on that branch.

## Suggested fix direction
Inspect `980a96f653` merge diff for `run.ts` around line 3543 to recover the dropped declaration/rename (possibly related to `resolveFinalAssistantVisibleText` failover handling).

## Evidence
Full CI diff analysis and logs: SE Run #488 step 10 report (`se-runs/se488-step10-merge-report.md`). Discovered during CI gate for PR #151.

Related: #134, PR #151

**Comment by NOVA-Openclaw** [comment]
## Fix design (SE run #489, steps 1–2 — PL scope assessment)

**Root cause (verified by 3-way comparison):**
- Pre-merge fork (`9e87477`) declared `const assistantForFailover = currentAttemptAssistant ?? sessionAssistantForCandidate;` (old line 3257) and used it throughout the assistant-failover block, including `resolveFinalAssistantVisibleText(assistantForFailover)`.
- Upstream v2026.7.1 names the equivalent binding `attemptAssistant`.
- The 980a96f653 merge resolution adopted upstream's name — current main line 2479: `const attemptAssistant = currentAttemptAssistant ?? sessionAssistantForCandidate;` — and converted all other usages (3423, 3434–3436, …) but **missed one**: line 3543 still reads `resolveFinalAssistantVisibleText(assistantForFailover)`.
- Upstream has no `assistantForFailover` identifier at all; the call site at 3543 is fork-specific code in the failover-decision block. Same-scope substitute exists and is semantically identical (same initializer expression as the pre-merge declaration).

**Fix:** one-line rename at `src/agents/embedded-agent-runner/run.ts:3543`:
`assistantForFailover` → `attemptAssistant`.

No API surface change, no behavior change vs pre-merge intent. Expected to unblock the 13 typecheck-gated CI jobs holding PR #151.

Proceeding through SE workflow: QA test design next.

**Comment by NOVA-Openclaw** [comment]
Fixed and merged to `main` via PR #153, squash-merge SHA `109aae4cd9f322ed9d79379ef01cdf8f1eb320ec`. Issue auto-closed by the merge commit's `Closes #152` reference. Full CI triage (all failures pre-existing/#134-attributable, none from this diff) is documented in PR #153's comments.
